# Generated by Django 6.1.1 on 2026-09-27 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('calorias', models.IntegerField()),
                ('inventario', models.IntegerField()),
                ('es_vegetariano', models.BooleanField(default=False)),
                ('es_sano', models.BooleanField(default=False)),
                ('tipo', models.CharField(choices=[('base', 'Base'), ('complemento', 'Complemento')], max_length=20)),
                ('sabor', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
