# Generated by Django 6.1.1 on 2026-09-30 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio_publico', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(choices=[('copa', 'Copa'), ('malteada', 'Malteada')], max_length=20)),
                ('vaso', models.CharField(blank=True, max_length=100)),
                ('volumen_onzas', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
